### ISSUE TITLE
Sort songs alphabetically in index.json

### ISSUE THREAD

**Issue by eutampieri** [eutampieri/songbook#2]
`index.json` is generated in `make_index.py`

**Comment by ArshErgon** [comment]
is it made on Flask?
and can please tell me how to run this project locally?

**Comment by eutampieri** [comment]
No, it isn't. If you look at the code I iterate over a set of files. The repo is all you need to run the project; I've added sample files that you have to rename to .json

**Comment by eutampieri** [comment]
No, I've provided you some sample files so you can actually work (and test) on something. Beware because the provided examples already produce a sorted output, but that's not true for every case. Perhaps sorting on the resulting Python list (by song title) before saving it to JSON is enough

**Comment by ArshErgon** [comment]
okay, cool. 
assign it to me
